### ISSUE TITLE
Изменить ссылку в github pages

### ISSUE THREAD

**Issue by xtoter** [bmstu-iu9/ptp2021-6-2d-game#10]
Сейчас github pages не работает. При его настройке выбирается ветка из которой github pages берет данные, но т.к. в нашем проекте главной является ветка master (ветка main отправлена в архив), а при создании репозитория главной для github pages выбрана main, то ссылка в github pages ведет в никуда.
Надо поменять в настройках репозитория для github pages поменять источник на корень ветки master (сейчас там readme, но позже будет меню)

**Comment by Mazdaywik** [comment]
Включил. Проверяйте.
